amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2   #从旋转角度考虑机器人里程计的旋转噪声
    alpha2: 0.2   #机器人平移分量中的里程计旋转噪音，噪声在机器人左右两边分布
    alpha3: 0.2   #机器人平移过程中的里程计平移噪音，沿着机器人前进方向分布
    alpha4: 0.2   #机器人旋转过程中的里程计平移噪音， 斜角方向上的运动噪声
    alpha5: 0.2   #仅适用于全向式（Omni）: 平移噪声。
    base_frame_id: "base_footprint"   #机器人基座frame名称。
    beam_skip_distance: 0.5   #设置忽略掉似然场模型中大多数粒子与地图不一致的光束，表示忽略的最大距离单位 (m) 。
    beam_skip_error_threshold: 0.9  #不匹配地图后的光束百分比，由于不一致而强制完全更新。
    beam_skip_threshold: 0.3   #需要跳过的光束（beams ）的百分比。
    do_beamskip: false   #是否在似然场模型（Likelihood field model）中进行波束（beam ）跳过。
    global_frame_id: "map"    #定位系统发布的坐标系名称。
    lambda_short: 0.1    #模型z_short部分的指数衰减参数。
    laser_likelihood_max_dist: 2.0    #在地图上进行障碍物充气的最大距离，用于likelihood_field模型。
    laser_max_range: 100.0   #要考虑的最大扫描范围，设为-1.0会直接使用激光报告的最大范围。
    laser_min_range: -1.0    #要考虑的最小扫描范围，-1.0将使用激光发出的的最小范围。
    laser_model_type: "likelihood_field"     #使用哪个模型，beam、likelihood_field 或 likelihood_field_prob。likelihood_field_prob 包含beamskip功能。
    max_beams: 60    #AMCL从参数 initial_pose* 设置机器人初始姿势，而不是等待话题 initial_pose ` 消息。
    max_particles: 2000     #所允许的最大粒子数。
    min_particles: 500    #所允许的最小粒子数。
    odom_frame_id: "odom"   #里程计使用的frame名称。
    pf_err: 0.05    #粒子过滤器总体误差。
    pf_z: 0.99   #粒子过滤器总体密度。
    recovery_alpha_fast: 0.0    #快速平均重量过滤器的指数衰减率，用于决定何时通过添加随机姿势来恢复。一个好的值可能是0.001。
    recovery_alpha_slow: 0.0    #慢平均重量过滤器的指数衰减率，用于通过添加随机姿势来决定何时恢复。一个好的值可能是0.001。
    resample_interval: 1   #重新采样前所需的过滤器更新数量。
    robot_model_type: "differential"     #插件类的完全限定类型。可以值为nav2_amcl::DifferentialMotionModel和nav2_amcl::OmniMotionModel。
    save_pose_rate: 0.5    #将最后估计姿态和协方差存储到参数服务器的最大速率 (Hz)，在变量 ~initial_pose_* 和 ~initial_cov_* 中。此保存的姿势将在后续运行中用于初始化过滤器 (-1.0表示禁用)。
    sigma_hit: 0.2   #用于设置在模型z_hit部分中使用的高斯模型的标准差。
    tf_broadcast: false   #用于设置是否广播坐标变换。参数False可以以防止amcl发布全局坐标系和里程计坐标系之间的坐标变换。 
    transform_tolerance: 1.0   #TF转换发布后的，该转换的所维持的有效时间。
    update_min_a: 0.2    #在执行过滤器更新之前需要的最小旋转角度。
    update_min_d: 0.25   #在执行过滤器更新之前需要的最小平移距离。
    z_hit: 0.5    #模型中z_hit部分的混合权重，所有使用的z权重之和必须为1。光束（Beam）模型使用所有共4个z_*权重，而似然模型（Likelihood）使用z_hit和z_rand权重。
    z_max: 0.05   #模型中z_max部分的混合权重，所有使用的z权重之和必须为1。光束（Beam）模型使用所有共4个z_*权重，而似然模型（Likelihood）使用z_hit和z_rand权重。
    z_rand: 0.5   #模型中z_rand部分的混合权重，所有使用的z权重之和必须为1。光束（Beam）模型使用所有共4个z_*权重，而似然模型（Likelihood）使用z_hit和z_rand权重。
    z_short: 0.05 #模型中z_short部分的混合权重，所有使用的z权重之和必须为1。光束（Beam）模型使用所有共4个z_*权重，而似然模型（Likelihood）使用z_hit和z_rand权重。
    scan_topic: scan  #要订阅的激光雷达话题名称。
    map_topic: map   #用于订阅地图的话题名称。
    set_initial_pose: false
    always_reset_initial_pose: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: false

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: false

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map    #参考框架。
    robot_base_frame: base_link    #行为树XML描述的路径。
    odom_topic: /odom    #里程计出版的主题
    enable_groot_monitoring: True    #
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:    #List of behavior tree node shared libraries.
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0    #运行控制器的频率 (赫兹)。 
    min_x_velocity_threshold: 0.001    #控制器服务器过滤接收到的里程表消息的速度部分，然后将其发送到控制器插件。低于该阈值 (以m/s为单位) 的里程表值将设置为0.0。
    min_y_velocity_threshold: 0.5     #控制器服务器过滤接收到的里程表消息的速度部分，然后将其发送到控制器插件。低于该阈值 (以m/s为单位) 的里程表值将设置为0.0。
    min_theta_velocity_threshold: 0.001    #控制器服务器过滤接收到的里程表消息的速度部分，然后将其发送到控制器插件。低于该阈值的里程计值 (以rad/s为单位) 将设置为0.0。
    progress_checker_plugin: "progress_checker"   #用于检查机器人进度的进度检查器插件的映射名称。
    goal_checker_plugin: "goal_checker"    #达到用于检查目标的目标检查器插件的映射名称。
    controller_plugins: ["FollowPath"]   #用于处理请求和参数的控制器插件的映射名称列表

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.25
      stateful: True
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.3
      max_vel_y: 0.0
      max_vel_theta: 0.8
      min_speed_xy: 0.0
      max_speed_xy: 0.3
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 2.0
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -2.0
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: false
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      footprint: "[ [0.8, 0.4], [0.8, -0.4], [-0.8, -0.4], [-0.8, 0.4] ]"
      #robot_radius: 0.9
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.2
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: false
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      footprint: "[ [0.9, 0.5], [0.9, -0.5], [-0.9, -0.5], [-0.9, 0.5] ]"
      #robot_radius: 0.9
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.2
      always_send_full_costmap: True    #是否每次更新都发送完整的成本图，而不是更新
  global_costmap_client:
    ros__parameters:
      use_sim_time: false
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "car_map.yaml"

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "back_up", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    back_up:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: false
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: false


    
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    use_sim_time: false
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      downsample_costmap: false           # 是否向下采样costmap到另一个分辨率进行搜索。
      downsampling_factor: 1              # 乘数因子向下采样成本图 (例如，如果5厘米成本图在2 downsample_factor ，10厘米输出)。
      allow_unknown: true                 # 是否允许在未知空间中遍历/搜索。
      max_iterations: 1000000             # 未能限制计算时间之前的最大搜索迭代次数，由-1禁用。
      max_planning_time: 5.0              # 最大计划时间 (秒)。
      motion_model_for_search: "DUBIN"    # 要搜索的运动模型枚举string。对于混合-A*节点，默认值为 "DUBIN" 。SE2的选项是DUBIN或REEDS_SHEPP。
      angle_quantization_bins: 72         # 用于SE2搜索的角仓数量。这可以是任何偶数，但是一个好的基线是64或72 (5度增量)。
      analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 3.0  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      minimum_turning_radius: 2.40        # 车辆的最小转弯半径 (米)。也用于平滑器计算最大曲率。
      reverse_penalty: 2.0                # 如果反向搜索，将启发式惩罚应用于SE2节点。仅用于 REEDS_SHEPP 运动模型。
      change_penalty: 0.0                 # 如果在搜索中改变方向 (例如从左到右)，将对SE2节点施加启发式惩罚。更改后默认禁用，以保证混合-A*planner的可接受性。
      non_straight_penalty: 1.2           # 如果在非直线方向搜索，则适用于SE2节点的启发式惩罚。
      cost_penalty: 2.0                   # 将启发式惩罚应用于SE2节点的姿态成本。允许混合-A*了解成本。Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      retrospective_penalty: 0.015
      lookup_table_size: 20.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: false     # 缓存障碍图动态编程距离扩展启发式算法在相同目标位置的辅助补充之间。如果costmap在很大程度上是静态的，则极大地加快了重新规划性能 (40倍)。Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      smooth_path: True                   # If true, does a simple and quick smoothing post-processing to the path

      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1e-10
        do_refinement: true